pub const AVATAR_BLOCK: [&str; 20] = [
    AVATAR_ROW_0,
    AVATAR_ROW_1,
    AVATAR_ROW_2,
    AVATAR_ROW_3,
    AVATAR_ROW_4,
    AVATAR_ROW_5,
    AVATAR_ROW_6,
    AVATAR_ROW_7,
    AVATAR_ROW_8,
    AVATAR_ROW_9,
    AVATAR_ROW_10,
    AVATAR_ROW_11,
    AVATAR_ROW_12,
    AVATAR_ROW_13,
    AVATAR_ROW_14,
    AVATAR_ROW_15,
    AVATAR_ROW_16,
    AVATAR_ROW_17,
    AVATAR_ROW_18,
    AVATAR_ROW_19,
];

pub static AVATAR_ROW_0: &str = r#"<span><span>             </span><span style="color:#9b837b">:</span><span style="color:#987f7b">'           </span><span style="color:#a28e7e">`</span><span style="color:#a9927d">"</span><span style="color:#b89886">]</span><span style="color:#c8af96">&amp;</span><span style="color:#c2bda5">w</span><span style="color:#a5a292">;</span><span>            </span></span>"#;
pub static AVATAR_ROW_1: &str = r#"<span><span>            </span><span style="color:#92857e">`            </span><span style="color:#9b948b">"</span><span style="color:#9c8f84">, </span><span style="color:#9e8c7b">~</span><span style="color:#b99f8b">*</span><span style="color:#f5ecc5">&amp;</span><span style="color:#fef1bc">$</span><span style="color:#edb678">@</span><span style="color:#b98960">H</span><span style="color:#9a7f6c">,</span><span>         </span></span>"#;
pub static AVATAR_ROW_2: &str = r#"<span><span>                          </span><span style="color:#9b9388">'</span><span style="color:#9d9380">'</span><span style="color:#9e947e">:  </span><span style="color:#d8c9ac">J</span><span style="color:#ecba7a">@</span><span style="color:#c38958">k</span><span style="color:#b47d59">}</span><span style="color:#dd9351">#</span><span style="color:#e8c891">&amp;</span><span style="color:#aaa08d">w</span><span>      </span></span>"#;
pub static AVATAR_ROW_3: &str = r#"<span><span>       </span><span style="color:#a1937c">,                    </span><span style="color:#999285">'</span><span style="color:#9d9286">; </span><span style="color:#a49383">*</span><span style="color:#c19f7b">]</span><span style="color:#bd8c5f">|</span><span style="color:#b07c58">:</span><span style="color:#d99253">]</span><span style="color:#fdd590">@</span><span style="color:#f7dfb0">@</span><span style="color:#b9a586">H</span><span style="color:#979086">,</span><span>    </span></span>"#;
pub static AVATAR_ROW_4: &str = r#"<span><span>      </span><span style="color:#a79e87">|</span><span style="color:#ad9d82">! </span><span style="color:#a19584">'                   </span><span style="color:#9b8879">, </span><span style="color:#a1927d">'</span><span style="color:#a2947b">'</span><span style="color:#af9778">|</span><span style="color:#b08d6d">;</span><span style="color:#ca9156">j</span><span style="color:#eab26d">M</span><span style="color:#d8b273">M</span><span style="color:#c8a96a">m</span><span style="color:#ceae63">k</span><span style="color:#b79c66">h</span><span>   </span></span>"#;
pub static AVATAR_ROW_5: &str = r#"<span><span>         </span><span style="color:#969288">'       </span><span style="color:#a18474">,</span><span style="color:#b7886d">j</span><span style="color:#bc846a">k</span><span style="color:#bd8066">k</span><span style="color:#c08266">k</span><span style="color:#c5896d">m</span><span style="color:#ca8d72">p</span><span style="color:#c6886e">@</span><span style="color:#c2846c">p</span><span style="color:#d2947d">g</span><span style="color:#e9bdaa">@</span><span style="color:#f4d8d1">$</span><span style="color:#fbe2db">$</span><span style="color:#dbad9b">@   </span><span style="color:#ac8c6b">;</span><span style="color:#c7a36b">#</span><span style="color:#cea964">k</span><span style="color:#cfa963">k</span><span style="color:#cfa95f">k</span><span style="color:#cfa95e">k</span><span style="color:#cea95a">k</span><span style="color:#c59a5d">@</span><span>  </span></span>"#;
pub static AVATAR_ROW_6: &str = r#"<span><span>       </span><span style="color:#a39b85">|</span><span style="color:#a69e89">;</span><span style="color:#9c9486">;</span><span style="color:#948280">.      </span><span style="color:#b18271">|</span><span style="color:#bf8068">|</span><span style="color:#c17d66">j</span><span style="color:#c07a62">|</span><span style="color:#c47a5f">j</span><span style="color:#ce8061">j</span><span style="color:#d88464">%</span><span style="color:#e18c69">]</span><span style="color:#ec926f">@</span><span style="color:#f59c81">@</span><span style="color:#fdb39d">&amp;</span><span style="color:#fdcbbe">&amp;</span><span style="color:#fed5cc">$</span><span style="color:#e6b4a0">$</span><span>   </span><span style="color:#b57c68">r</span><span style="color:#ab7764">'</span><span style="color:#af7e66">!</span><span style="color:#af8063">|</span><span style="color:#ba8161">|</span><span style="color:#c38c67">m</span><span style="color:#ab8366">,</span><span>   </span></span>"#;
pub static AVATAR_ROW_7: &str = r#"<span><span style="color:#848280">    </span><span style="color:#9b957e">,</span><span style="color:#a39c86">|</span><span style="color:#a19882">`</span><span style="color:#a89f87">|</span><span style="color:#b2a58c">|</span><span style="color:#ad927a">|</span><span style="color:#b67166">/</span><span style="color:#b0746b">=   </span><span style="color:#ad836f">;</span><span style="color:#b47b67">j</span><span style="color:#b97c66">l</span><span style="color:#bc7e66">|</span><span style="color:#c07a66">l</span><span style="color:#c17964">l</span><span style="color:#c3785e">j</span><span style="color:#cc7c5f">j</span><span style="color:#da8567">]</span><span style="color:#ea9272">K</span><span style="color:#ee9374">@</span><span style="color:#ed9273">@</span><span style="color:#f6a187">$</span><span style="color:#febaa8">$</span><span style="color:#fdc9bd">&amp;</span><span style="color:#d5a18f">L</span><span style="color:#c28f77">]</span><span style="color:#c6927b">       </span><span style="color:#a87766">`</span><span style="color:#b07d68">!</span><span style="color:#a47c6a">,</span><span>  </span></span>"#;
pub static AVATAR_ROW_8: &str = r#"<span><span style="color:#878583"> </span><span style="color:#9b9689">;  </span><span style="color:#9f9a86">'</span><span style="color:#a29b84">,</span><span style="color:#aa9d85">;</span><span style="color:#ab9f84">|</span><span style="color:#a09881">' </span><span style="color:#b47c6e">j</span><span style="color:#b66d63">;</span><span style="color:#ba7869">(</span><span style="color:#b17e6d">)</span><span style="color:#aa7f6e">;</span><span style="color:#c08368">l</span><span style="color:#be8267">|</span><span style="color:#b47f67">|</span><span style="color:#ac7e6a">"</span><span style="color:#a77d6d">'</span><span style="color:#a67c6d">`</span><span style="color:#a67c6d">'</span><span style="color:#ab7b66">'</span><span style="color:#b67d66">*</span><span style="color:#cf8367">]</span><span style="color:#e3896b">[</span><span style="color:#da8668">%</span><span style="color:#d2886c">|</span><span style="color:#d1947b">]</span><span style="color:#dea58b">g</span><span style="color:#bf9388">H      </span><span style="color:#b08a69">;</span><span style="color:#a97a64">, </span><span style="color:#b29e8e">]</span><span style="color:#b6ab9a">h</span><span style="color:#9d9480">:</span><span style="color:#a47c6a">,</span></span>"#;
pub static AVATAR_ROW_9: &str = r#"<span><span style="color:#948b81"> </span><span style="color:#a49c88">|</span><span style="color:#a49982">,</span><span style="color:#a39780">;</span><span style="color:#a39983">|</span><span style="color:#a89c80">|</span><span style="color:#a79b7c">;</span><span style="color:#a1947a">,</span><span style="color:#9c8f7c">,  </span><span style="color:#98807b">`</span><span style="color:#a37b72">'</span><span style="color:#ae7b69">|</span><span style="color:#b17965">|</span><span style="color:#ba8068">|</span><span style="color:#bd7f65">|</span><span style="color:#bb7c62">!</span><span style="color:#b37d66">;</span><span style="color:#a57a69">,  </span><span style="color:#9f796c">,</span><span style="color:#a17a6f">,</span><span style="color:#b17666">|</span><span style="color:#e59a85">%</span><span style="color:#e29f92">@</span><span style="color:#cb7c68">y</span><span style="color:#d38b76">@</span><span style="color:#eca994">&amp;</span><span style="color:#b9908b">U      </span><span style="color:#b79169">|</span><span style="color:#bc9069">|</span><span style="color:#b29a7f">|</span><span style="color:#a39880">,</span><span style="color:#a19983">,</span><span style="color:#a09582">`</span><span> </span></span>"#;
pub static AVATAR_ROW_10: &str = r#"<span><span style="color:#b4a17f">j</span><span style="color:#b09c7b">|</span><span style="color:#af9c78">|</span><span style="color:#b3a07c">j</span><span style="color:#b29c78">|</span><span style="color:#b49d78">|</span><span style="color:#b79f7d">i</span><span style="color:#b49d7d">|</span><span style="color:#b49f7f">i</span><span style="color:#a19585">"   </span><span style="color:#b17e6e">|</span><span style="color:#b7816f">|</span><span style="color:#b8816a">!</span><span style="color:#b97864">|</span><span style="color:#be7862">l</span><span style="color:#c1785f">j</span><span style="color:#c47d63">j</span><span style="color:#c48067">k</span><span style="color:#c07e67">k</span><span style="color:#b77864">|</span><span style="color:#b67363">|</span><span style="color:#b87062">|</span><span style="color:#d58170">]</span><span style="color:#fbcec8">@</span><span style="color:#f5a792">%</span><span style="color:#fbaa97">@</span><span style="color:#febaab">$      </span><span style="color:#a49178">;</span><span style="color:#b49978">|</span><span style="color:#9f8b77">` </span><span style="color:#969184">'</span><span style="color:#9d9885">' </span><span style="color:#afa593">j</span></span>"#;
pub static AVATAR_ROW_11: &str = r#"<span><span style="color:#a29682">"</span><span style="color:#ad9e7d">|</span><span style="color:#b19f7c">|</span><span style="color:#b29d7b">!</span><span style="color:#b49f7a">|</span><span style="color:#b49d7d">k</span><span style="color:#aa987f">*</span><span style="color:#998c81">`   </span><span style="color:#b4b6ba">@</span><span style="color:#a2867e">;</span><span style="color:#b17c6b">|</span><span style="color:#b07f6e">|</span><span style="color:#b3816c">|</span><span style="color:#b17765">|</span><span style="color:#b17566">"</span><span style="color:#b17264">!</span><span style="color:#b77363">!</span><span style="color:#bd7b65">|</span><span style="color:#b97766">|</span><span style="color:#ad7064">'</span><span style="color:#b17468">"</span><span style="color:#b77464">*</span><span style="color:#c67361">j</span><span style="color:#f6b0a4">8</span><span style="color:#eb9183">@</span><span style="color:#e48769">@</span><span style="color:#c98b7f">C    </span><span style="color:#a08975">,</span><span style="color:#a1856e">,</span><span style="color:#b48b76">j</span><span style="color:#ba8a78">|    </span><span style="color:#a19885">'</span><span style="color:#ada393">[</span></span>"#;
pub static AVATAR_ROW_12: &str = r#"<span><span style="color:#81807f"> </span><span style="color:#96897b">'         </span><span style="color:#b5b8bc">k</span><span style="color:#b09e9c">h</span><span style="color:#a97c71">' </span><span style="color:#a97a6e">`</span><span style="color:#a9786a">' </span><span style="color:#ab7869">'</span><span style="color:#ad7769">|</span><span style="color:#af796a">; </span><span style="color:#b07167">"</span><span style="color:#bd7062">]</span><span style="color:#df8474">%</span><span style="color:#ea998e">@</span><span style="color:#fdb4a7">&amp;</span><span style="color:#e8997f">@</span><span style="color:#ad8980">*    </span><span style="color:#9a8c7e">, </span><span style="color:#b18575">!</span><span style="color:#ae796b">"</span><span style="color:#a7786a">`</span><span>      </span></span>"#;
pub static AVATAR_ROW_13: &str = r#"<span><span>           </span><span style="color:#96979a">"</span><span style="color:#b0b3b2">j</span><span style="color:#afa6a2">k</span><span style="color:#a38a7f">,    </span><span style="color:#ab7a6a">|</span><span style="color:#b47964">|</span><span style="color:#bc7a66">!</span><span style="color:#bc7962">j</span><span style="color:#cb8068">m</span><span style="color:#dd8e79">@</span><span style="color:#f7aea3">@</span><span style="color:#f3b8ac">@             </span><span style="color:#9d7f74">:</span><span>   </span></span>"#;
pub static AVATAR_ROW_14: &str = r#"<span><span>            </span><span style="color:#9a9b9a">'</span><span style="color:#b1acaa">j</span><span style="color:#aea59d">|</span><span style="color:#a99785">!</span><span style="color:#a48678">;</span><span style="color:#a17d74">, </span><span style="color:#aa7667">,</span><span style="color:#b57e6c">w</span><span style="color:#ad7d6d">/</span><span style="color:#af8174">|</span><span style="color:#c38f7e">|</span><span style="color:#d49e8c">l</span><span style="color:#dab4a7">[               </span><span style="color:#94837b">`</span><span>  </span></span>"#;
pub static AVATAR_ROW_15: &str = r#"<span><span>             </span><span style="color:#a5a29e">j</span><span style="color:#b7a598">j</span><span style="color:#c89e8b">g</span><span style="color:#c79f89">@</span><span style="color:#bfa191">p</span><span style="color:#c5b1ae">#</span><span style="color:#af9394">*</span><span style="color:#a5837e">^</span><span style="color:#cdbabd">#</span><span style="color:#ded1d6">M</span><span style="color:#d5c9c5">%</span><span style="color:#e1dedd">M</span><span style="color:#dee3e2">M</span><span style="color:#cdd7df">M</span><span style="color:#c6ced6">%</span><span style="color:#c2ccd1">@</span><span style="color:#c4cfda">@</span><span style="color:#c9d7e7">@</span><span style="color:#d7e5ea">@</span><span style="color:#e0e7e9">$</span><span style="color:#a9a8ac">M</span><span>          </span></span>"#;
pub static AVATAR_ROW_16: &str = r#"<span><span>            </span><span style="color:#a08880">,</span><span style="color:#bd9078">%</span><span style="color:#c88d6c">k</span><span style="color:#c98768">{</span><span style="color:#d5856f">j</span><span style="color:#ee9e8c">@</span><span style="color:#e29681">%</span><span style="color:#dc967f">%</span><span style="color:#de9b87">%</span><span style="color:#e39a87">N</span><span style="color:#e59a88">N</span><span style="color:#c9a490">@</span><span style="color:#bea794">]</span><span style="color:#c4afa0">%</span><span style="color:#c1b4ac">%</span><span style="color:#c3b8b2">%</span><span style="color:#c7c4c3">]</span><span style="color:#ccd5e0">B</span><span style="color:#d4e7fb">$</span><span style="color:#e4fdff">$</span><span style="color:#f0fdfd">$</span><span>           </span></span>"#;
pub static AVATAR_ROW_17: &str = r#"<span><span>         </span><span style="color:#928580">,</span><span style="color:#b38e7e">p</span><span style="color:#c69074">k</span><span style="color:#c79073">j</span><span style="color:#c78e72">j</span><span style="color:#c78e72">k</span><span style="color:#cc8b6e">%</span><span style="color:#e39580">%</span><span style="color:#febcb0">&amp;</span><span style="color:#f4b2a8">&amp;</span><span style="color:#d38f81">g</span><span style="color:#b18077">|</span><span style="color:#b97863">j</span><span style="color:#cf8066">]</span><span style="color:#d19278">%</span><span style="color:#b29077">|</span><span style="color:#c1a590">]</span><span style="color:#c0aea0">k</span><span style="color:#c2b5ad">%</span><span style="color:#c7c2bb">]</span><span style="color:#ccd4e0">B</span><span style="color:#d5eafc">$</span><span style="color:#e8fdff">$</span><span style="color:#d5dee1">K</span><span>           </span></span>"#;
pub static AVATAR_ROW_18: &str = r#"<span><span>         </span><span style="color:#a18579">"</span><span style="color:#b78a72">*</span><span style="color:#c48b6e">k</span><span style="color:#c3896f">j</span><span style="color:#c28871">!</span><span style="color:#c0886d">|</span><span style="color:#c38569">j</span><span style="color:#e09a83">g</span><span style="color:#e89b86">@</span><span style="color:#e29380">%</span><span style="color:#e39783">%</span><span style="color:#eba995">%</span><span style="color:#f2b0a5">@</span><span style="color:#edb6aa">&amp;</span><span style="color:#d1b5aa">U</span><span style="color:#bda89d">N</span><span style="color:#bca086">j</span><span style="color:#beaa9a">j</span><span style="color:#c0b3aa">k</span><span style="color:#c7bfb9">]</span><span style="color:#ced5e3">B</span><span style="color:#dbeffc">$</span><span style="color:#e8fdfe">$</span><span>            </span></span>"#;
pub static AVATAR_ROW_19: &str = r#"<span><span>             </span><span style="color:#988176">`</span><span style="color:#a08172">'</span><span style="color:#ae7f6b">*</span><span style="color:#cf9079">%</span><span style="color:#efae98">B</span><span style="color:#edad96">M</span><span style="color:#de9982">M</span><span style="color:#d89377">@</span><span style="color:#d0856c">w</span><span style="color:#d2947e">]</span><span style="color:#d8b0a4">$</span><span style="color:#bdabad">m</span><span style="color:#b19b8b">|</span><span style="color:#b09888">i</span><span style="color:#af9d8f">*</span><span style="color:#ab9f98">*</span><span style="color:#a4a6aa">*</span><span style="color:#959b9d">`</span><span>             </span></span>"#;

pub const INFO_BLOCK: [&str; 20] = [
    INFO_ROW_0,
    INFO_ROW_1,
    INFO_ROW_2,
    INFO_ROW_3,
    INFO_ROW_4,
    INFO_ROW_5,
    INFO_ROW_6,
    INFO_ROW_7,
    INFO_ROW_8,
    INFO_ROW_9,
    INFO_ROW_10,
    INFO_ROW_11,
    INFO_ROW_12,
    INFO_ROW_13,
    INFO_ROW_14,
    INFO_ROW_15,
    INFO_ROW_16,
    INFO_ROW_17,
    INFO_ROW_18,
    INFO_ROW_19,
];

pub static INFO_ROW_0: &str = r#"<a href="mailto:contact@hansbaker.com" target="_blank"><span class="text-brightCyan">contact</span>@<span class="text-brightCyan">hansbaker.com</span></a> <button class="text-brightWhite cursor-pointer" onclick="navigator.clipboard.writeText('contact@hansbaker.com').then(() => alert('copied: contact@hansbaker.com'))">📋</button>"#;
pub static INFO_ROW_1: &str = r#"---------------------"#;
pub static INFO_ROW_2: &str = r#"<span class="text-brightCyan">Name</span>: Hans Baker"#;
pub static INFO_ROW_3: &str = r#"<span class="text-brightCyan">Location</span>: USA"#;
pub static INFO_ROW_4: &str =
    r#"<span class="text-brightCyan">Occupation</span>: Software Engineering Leader"#;
pub static INFO_ROW_5: &str = r#"<span class="text-brightCyan">Years Exp</span>: 8+"#;
pub static INFO_ROW_6: &str = r#"<span class="text-brightCyan">Languages</span>: <span class="whitespace-nowrap"><i class="devicon-go-plain text-brightWhite"></i> Go</span>, <span class="whitespace-nowrap"><i class="devicon-rust-plain text-brightWhite"></i> Rust</span>, <span class="whitespace-nowrap"><i class="devicon-python-plain text-brightWhite"></i> Python</span>, <span class="whitespace-nowrap"><i class="devicon-typescript-plain text-brightWhite"></i> TypeScript</span>... Adaptable"#;
pub static INFO_ROW_7: &str = r#"<span class="text-brightCyan">Tech</span>: <span class="whitespace-nowrap"><i class="devicon-postgresql-plain text-brightWhite"></i> Postgres</span>, <span class="whitespace-nowrap"><i class="devicon-redis-plain text-brightWhite"></i> Redis</span>, <span class="whitespace-nowrap"><i class="devicon-docker-plain text-brightWhite"></i> Docker</span>, <span class="whitespace-nowrap"><i class="devicon-terraform-plain text-brightWhite"></i> Terraform</span>... Resourceful"#;
pub static INFO_ROW_8: &str = r#"<span class="text-brightCyan">Soft Skills</span>: Leadership, communication, collaboration... Interpersonal"#;
pub static INFO_ROW_9: &str = r#"<span class="text-brightCyan">Values</span>: Accountability, empathy, grit, excellence... Principled"#;
pub static INFO_ROW_10: &str = r#"<span class="text-brightCyan">Education</span>: Comp Sci (no degree), B.A. in Phil... Lifelong Learner"#;
pub static INFO_ROW_11: &str =
    r#"<span class="text-brightCyan">Dev Env</span>: Tmux & Neovim in WSL2 (tty)"#;
pub static INFO_ROW_12: &str =
    r#"<span class="text-brightCyan">Coffee</span>: Black as midnight on a moonless night"#;
pub static INFO_ROW_13: &str =
    r#"<span class="text-brightCyan">Hobbies</span>: Far too many... 😅"#;
pub static INFO_ROW_14: &str = r#""#;
pub static INFO_ROW_15: &str = r#"<span class="text-brightCyan">Pages</span>: <span class="whitespace-nowrap"><a class="text-blue" href="/blog">/blog</a></span> | <span class="whitespace-nowrap"><a class="text-blue" href="/cv">/cv</a> (resume)</span> | <span class="whitespace-nowrap"><a class="text-blue" href="https://mines.hansbaker.com">mines.</a> (game)</span>"#;
pub static INFO_ROW_16: &str = r#"<span class="text-brightCyan">Links</span>: <a class="text-blue whitespace-nowrap" href="https://github.com/BakerNet"><i class="devicon-github-plain text-brightWhite"></i> @BakerNet</a> | <a class="text-blue whitespace-nowrap" href="https://linkedin.com/in/hansbaker"><i class="devicon-linkedin-plain text-brightWhite"></i> /in/hansbaker</a>"#;
pub static INFO_ROW_17: &str = r#""#;
pub static INFO_ROW_18: &str = r#"<span class="bg-black">   </span><span class="bg-red">   </span><span class="bg-green">   </span><span class="bg-yellow">   </span><span class="bg-blue">   </span><span class="bg-purple">   </span><span class="bg-cyan">   </span><span class="bg-white">   </span>"#;
pub static INFO_ROW_19: &str = r#"<span class="bg-brightBlack">   </span><span class="bg-brightRed">   </span><span class="bg-brightGreen">   </span><span class="bg-brightYellow">   </span><span class="bg-brightBlue">   </span><span class="bg-brightPurple">   </span><span class="bg-brightCyan">   </span><span class="bg-brightWhite">   </span>"#;
